### ISSUE TITLE
Error: wxALIGN_CENTRE_HORIZONTAL and wxALIGN_RIGHT can't be used together

### ISSUE THREAD

**Issue by AndyCGN** [makerbase-mks/MKS-TOOL#1]
got this error after selecting board and click on continue. using python 2.7.16 and install wxPython via pip.

File "C:\Daten\3d Druck\Drucker\sapphire PULS-2\MKS-TOOL-master\mainFrame.py", line 2165, in initview
    self.cflefttopsizer.Add(self.cfone, 0, wx.ALL|wx.ALIGN_CENTER|wx.ALIGN_RIGHT, border=1)
wx._core.wxAssertionError: C++ assertion "((m_flag) & (wxALIGN_CENTRE_HORIZONTAL | wxALIGN_RIGHT)) != (wxALIGN_CENTRE_HORIZONTAL | wxALIGN_RIGHT)" failed at ..\..\src\common\sizer.cpp(215) in wxSizerItem::wxSizerItem(): wxALIGN_CENTRE_HORIZONTAL and wxALIGN_RIGHT can't be used together

**Comment by zhpt** [comment]
Thank you for your comment. Code updated and please try again it.
