### ISSUE TITLE
Online configurator dead

### ISSUE THREAD

**Issue by Ratisse** [makerbase-mks/MKS-TOOL#10]
The online MKS Tool returns a 502 bad gateaway error, Can we hope to have a MKS tool application update taking in account the MKS_TFT35 display soon?

**Comment by mks-viva** [comment]
Hi! https://www.baizhongyun.cn/home/mkstoolview

**Comment by Ratisse** [comment]
OK, thank you

**Comment by bleachcow** [comment]
its down again
