### ISSUE TITLE
mks Wifi ID Number

### ISSUE THREAD

**Issue by rikvandersteen** [makerbase-mks/MKS-TOOL#11]
Hello  

i have a makerbase touch screen and a mks wifi module  
it is connected to a printer from zonestar brand  , 
the problem is i want to connect this printer to the cloud but in the menu there is no screen to take picture so that i have a id number for in the cloud app 

is there a other way to get the ID number 

within a lokal LAN it worked

**Comment by makerbase-mks** [comment]
@rikvandersteen ,Do you mean you cannot find the QRcode on the LCD? Have you enabled the cloud function on your board?

**Comment by rikvandersteen** [comment]
i found out that is was dissabled in the config from the manufactor

i have a other guestion but i will make a new toppic for it
